version: '3'

tasks:
  start-server:
    cmds:
      - go run ./app

  unit-tests:
    cmds:
      - go test -v ./app/...

  integration-tests:
    cmds:
      - go test -v ./tests/...

  basic-dig-test:
    cmds:
      - dig @127.0.0.1 -p 2053 +noedns +qid=1234 codecrafters.io
